### PR TITLE
Conclusions

### PR DESCRIPTION
**Pull request by kallerosenbaum**
Fixes issue #94

### CODE REVIEW

**Comment by kallerosenbaum** [comment]
@MartaTurchetta for some reason I can't add you as a reviewer on PRs, so I'll have to summon you though a comment instead. Please review this when you have time. Thanks.

**Comment by kallerosenbaum** [comment]
@adamjonas do you know why I can't set @MartaTurchetta as reviewer on PRs?

**Comment by kallerosenbaum** [comment]
> @adamjonas do you know why I can't set @MartaTurchetta as reviewer on PRs?

I invited her as member of the org, maybe that does the trick.

**Comment by MartaTurchetta** [comment]
Hi there! Sorry for the late reply but I never received your invitation. Or better, I received an invitation but when I tried to open it the system said "Invitation not found" and it hasn't changed. @kallerosenbaum can you try to invite me again please?

**Comment by kallerosenbaum** [comment]
@MartaTurchetta new invitation sent (I hope).

**Comment by MartaTurchetta** [comment]
Yay! Received and accepted. Sorry, the issue was probably that I took too long to accept the invitation

**Comment by kallerosenbaum** [comment]
I added you as a reviewer now.

**Comment by kallerosenbaum** [comment]
Note that adding someone as a reviewer doesn't mean that they get some priveleges, it's just a way for me to say that I'd like them to review. Anyone can review.

**Comment by RandyMcMillan** [comment]
I'd love to help review

**Comment by kallerosenbaum** [comment]
@RandyMcMillan That's great! Just dig in.

Right now, we won't make any substantial changes to the content, but any errors/typos you can find is great. What would provide us the most value would be a good read-through, and comment on any issues you find. If you don't want to read the whole thing, just pick a chapter that catches your interest. Also, while reading make sure the links still work and point to the right page. Thanks.

**Comment by MartaTurchetta** [comment]
Hi there! Sorry for the delay. I reviewed all the conclusions and they seem alright to me, as they make great summaries for every chapter's key points. Great job :)

**Review by MartaTurchetta — APPROVED** [review]

**Comment by kallerosenbaum** [comment]
Thanks @MartaTurchetta !

**Pull request merged**
