### PR TITLE
Introduce initial banner images

### PR DESCRIPTION
**Pull request by jarolrod**
This introduces images as banners for each section. I was initially going to write a post explaining each image, but I've already spent a massive amount of time generating images I like. This will have to do.

The only ones I'm not absolutely happy with are open source, privacy, and scaling. I think these are good, but I'd love to see other people give their opinion on what kind of image they think best fits each section. All images I've generated can be found here: https://www.midjourney.com/app/users/488921812525383682/

### CODE REVIEW

**Comment by jarolrod** [comment]
Note: the images here can be optimized for size without comprising much on quality, let me know if I should do this

**Comment by jarolrod** [comment]
| 1. Decentralization | 2. Trustlessness | 3. Privacy | 
| ------------------- | ---------------- | ---------- |
| Screen Shot 2023-01-12 at 12 03 50 AM |  Screen Shot 2023-01-12 at 12 03 54 AM | Screen Shot 2023-01-12 at 12 03 57 AM | 


| 4. Finite Supply | 5. Upgrading | 6. Adversarial Thinking |
| ---------------- | ------------ | ----------------------- |
| Screen Shot 2023-01-12 at 12 03 59 AM |Screen Shot 2023-01-12 at 12 04 02 AM |Screen Shot 2023-01-12 at 12 04 06 AM |  


| 7. Open Source | 8. Scaling | 9. WSHTF |
| -------------- | ---------- | -------- |
| Screen Shot 2023-01-12 at 12 04 08 AM | Screen Shot 2023-01-12 at 12 04 11 AM |Screen Shot 2023-01-12 at 12 04 15 AM |

**Comment by adamjonas** [comment]
My favorites are decentralization, privacy, finite supply, and upgrading. 

I'd be interested in what @kallerosenbaum has to say but I'd be open to seeing alternatives to the others. 

Overall, I think this is a great first attempt. Thanks @jarolrod!

**Comment by kallerosenbaum** [comment]
The images are beautiful! Great work!

What tool did you use to produce them? I'm asking because if the source format is open source maybe we should add the actual source files for the images and generate the .png files using a Makefile. I did that with "grokking bitcoin" and it's really nice to have the actual sources in the repo and generate everything from there. I volunteer to experiment with the sources to see what I can come up with.

The excalidraw images in this repo are the actual source files, because the source excalidraw data is embedded in them.

**Comment by jarolrod** [comment]
@kallerosenbaum they're generated with midjourney. As far as I know, while midjourney works it outputs a .webp then when it's done it outputs a finished PNG file; so I don't think I'm able to provide a source file

**Comment by adamjonas** [comment]
@kallerosenbaum do you have specific favorites/would request any changes, or do we want to merge and iterate on what he has provided?

**Comment by kallerosenbaum** [comment]
@jarolrod I'm not sure about photoshop. I suppose they use some proprietary format. Let's keep the png files as they are in the repo so that we don't lose the high-res versions. As for resizing to make the images more lightweight, that can easilty be made in a Makefile (I can make that happen). Would y'all be able to install ImageMagick on your machines?

This is what I think about the images (+ more fantastic, - less fantastic):

1. Nice visual, but very generic
2. - Fun, but less appealing
3. Pleasing and I like the detail
4. + Extremely nice to look at. Maybe an hour-glass isn't the best representation of finite supply, but it is finite.
5. Nice visual and quite fitting for the subject
6. Looks really good.
7. + Great stuff. I love the exposure of the pipes and stuff. Very open sourcey.
8. - I get a bit dizzy, and don't quite understand what it tries to say to me.
9. + Funny and good looking.

I think they're all good, but if anything needs rework, I think it's 2 and 8

**Comment by kallerosenbaum** [comment]
And I don't have any better ideas for 2 and 8. I'd say merge for now and iterate.

**Comment by jarolrod** [comment]
@kallerosenbaum aside from the make stuff, core has a nice image optimizing script we have in a maintainers repo that could strip and optimize for disk size without changing the current pixel dimensions, I can give the images here a pass with that if you'd like: https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/optimize-pngs.py

**Comment by kallerosenbaum** [comment]
@jarolrod I'd say leave it for now.

**Comment by adamjonas** [comment]
I used [imageoptim](https://imageoptim.com/) for some compression. Got some savings but they are still big.

Screen Shot 2023-01-12 at 8 00 30 PM

**Comment by jarolrod** [comment]
@adamjonas we can get the file sizes to be reasonably small, there’s many ways to do this. I can create an issue about this to continue discussions on that.

**Comment by jarolrod** [comment]
@kallerosenbaum @adamjonas Compressed images to be less than or about 300kb each keeping most of the color fidelity and standardizing all images to a resolution of 2304 × 1536, total image package size is now 2.6mb versus 50+mb. Compare the images being added in this branch to the following, there should be no discernible difference:

|   1. Decentralization   |  2. Trustlessness   |      3. Privacy     | 
| ----------------------- | ------------------- | ------------------- |
|  decentralization-banner | trustlessness-banner | privacy-banner |

| 4. Finite Supply | 5. Upgrading | 6. Adversarial Thinking |
| ---------------- | ------------ | ----------------------- |
| finitesupply-banner | upgrading-banner |  adversarialthinking-banner |

| 7. Open Source | 8. Scaling | 9. WSHTF |
| -------------- | ---------- | -------- |
| opensource-banner | scaling-banner | shtf-banner |

**Comment by adamjonas** [comment]
The fidelity of those look great to me.

**Comment by adamjonas** [comment]
To muddy the waters.... Here are some scaling alternatives.
Scaling 2
Scaling 1
Scaling 8
Scaling 7
Scaling 6

**Comment by adamjonas** [comment]
and some options for trustlessness:

A.
Trustlessness 9

B.
Trustlessness 6

C.
Trustlessness 5

D.
Trustlessness 4

E.
Trustlessness 3

F.
Trustlessness 2

G.
Trustlessness 14

H.
Trustlessness 13

I.
Trustlessness 12

J.
Trustlessness 11

**Comment by kallerosenbaum** [comment]
Thanks Adam! I like Scaling A and Trustlessness D best.

**Comment by adamjonas** [comment]
@jarolrod would you be up for including those into your PR?

**Comment by jarolrod** [comment]
Updated from 1381432 to dcbc28c

Changes: 
- updated images to compressed jpg version for purposes of the keep the site accessible to load on all internet speeds, I have the original files if we need them for whatever reason
- For `Scaling A` and `Trustlessness D`, I've expanded the images to be wider (I think all the banners should be an aspect ratio of 3:2) drawing in the correct context and corrected some colors, I then adding them here

| Scaling A Original | Scaling A Expanded |
| ------------------ | ------------------ |
| 212389359-1275e4fa-e8ad-49cf-9645-453cd12f271a | scaling-banner |


| Trustlessness D Original | Trustlessness D Expanded |
| ------------------------ | ------------------------ |
| 212389935-fc1bbd60-bc7d-4e60-b9c1-636859eb3fce-2 | trustlessness-banner |

**Comment by adamjonas** [comment]
ACK [dcbc28c](https://github.com/bitcoin-dev-philosophy/btcphilosophy/pull/48/commits/dcbc28c70d913361bb2239357e577d984281241d). We've got ourselves a V1. 

Thanks @jarolrod for making this happen.

**Pull request merged**
